Fix cmdline attribute box in process handles.
Due to a removal of the cmdline attribute in process handles,
many pants commands fail with: AttributeError: 'ProcessHandleProcfs' object has no attribute 'cmdline'